service: serverless-chat
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
      - Effect: Allow
        Action:
            - "execute-api:ManageConnections"
        Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"
      - Effect: Allow
        Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:BatchGetItem"
            - "dynamodb:BatchWriteItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
        Resource:
            - "arn:aws:dynamodb:ap-southeast-2:*:*"
  stage: dev
  region: ap-southeast-2
  websocketApiName: gov-chat-api
  websocketApiRouteSelectionExpression: $request.body.action

functions:
    connectionManager:
        handler: handler.connection_manager
        events:
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
    defaultMessage:
        handler: handler.default_message
        events:
            - websocket:
                route: $default
    getRecentMessages:
        handler: handler.get_recent_messages
        events:
            - websocket:
                route: getRecentMessages
    sendMessage:
        handler: handler.send_message
        events:
            - websocket:
                route: sendMessage
    ping:
        handler: handler.ping
        events:
            - http:
                path: ping
                method: get

plugins:
  - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: true
        noDeploy: []
